### ISSUE TITLE
"There is a programable error in your configuration file:"

### ISSUE THREAD

**Issue by gerroon** [JacquesLucke/animation_nodes_manual#57]
I tried with system's python and virtualenv, same result

sphinx-build -b html docs build
Running Sphinx v1.7.9

Configuration error:
There is a programable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/sphinx/config.py", line 161, in __init__
    execfile_(filename, config)
  File "/usr/lib/python3/dist-packages/sphinx/util/pycompat.py", line 150, in execfile_
    exec_(code, _globals)
  File "conf.py", line 5, in <module>
    import sphinx_rtd_theme
ModuleNotFoundError: No module named 'sphinx_rtd_theme'

**Comment by gerroon** [comment]
never mind tried with py3 env and it works
