### ISSUE TITLE
FastNoise

### ISSUE THREAD

**Issue by GiorgioAdolfo** [JacquesLucke/animation_nodes_manual#79]
Hello, tried to compile AN on Centos 7 and got this:

Traceback (most recent call last): File "/opt/Autodesk/flame_2021/blender-2.83-839fe335d2d6-linux64/2.83/scripts/modules/addon_utils.py", line 351, in enable mod = import(module_name) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/init.py", line 166, in <module> auto_load.init() File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 23, in init modules = get_all_submodules(Path(file).parent) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 51, in get_all_submodules return list(iter_submodules(directory, directory.name)) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/auto_load.py", line 55, in iter_submodules yield importlib.import_module("." + name, package_name) File "/opt/Autodesk/flame_2021/blender-2.83-839fe335d2d6-linux64/2.83/python/lib/python3.7/importlib/init.py", line 127, in import_module return _bootstrap._gcd_import(name[level:], package, level) File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/init.py", line 1, in <module> from . node_base import Noise3DNodeBase File "/opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/node_base.py", line 6, in <module> from . wrapper import ( ImportError: /opt/Autodesk/flame_2021/.config/blender/2.83/scripts/addons/animation_nodes/libs/FastNoiseSIMD/wrapper.cpython-37m-x86_64-linux-gnu.so: undefined symbol: _ZN22FastNoiseSIMD_internal16FastNoiseSIMD_L3C1Ei</module></module></module>

Any suggestions, help?!
Thank you!!

**Comment by OmarEmaraDev** [comment]
I think this is identical to https://github.com/JacquesLucke/animation_nodes/discussions/1692.
